In [120]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [121]:
N = 12
P = 12
# make an empty data set
school = np.zeros((N, P))
print(school)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [122]:
court_y = np.ones((4,4)) +1
print(court_y)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [123]:
school [4:8,4:8] = court_y
print(school)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [127]:
for i in range(N):
    for j in range(P):
        if school[i,j] == 2:
            num_neighbor = 1
            left = max(0, i - num_neighbor)
            right = max(0, i + num_neighbor + 1)
            bottom = max(0, j - num_neighbor)
            top = max(0, j + num_neighbor + 1)
            for k in range(left,right):
                for a in range(bottom,top):
                   if school[k,a] != 2:
                        school[k,a]= 1
print(school)
           


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 2. 2. 2. 2. 1. 0. 0. 0.]
 [0. 0. 0. 1. 2. 2. 2. 2. 1. 0. 0. 0.]
 [0. 0. 0. 1. 2. 2. 2. 2. 1. 0. 0. 0.]
 [0. 0. 0. 1. 2. 2. 2. 2. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [135]:
for i in range(N):
    for j in range(P):
        if school[i,j] == 2:
            num_neighbor = 1
            left = max(1, i - num_neighbor)
            right = max(1, i + num_neighbor + 1)
            bottom = max(1, j - num_neighbor)
            top = max(1, j + num_neighbor + 1)
            for k in range(left,right):
                for a in range(bottom,top):
                   if school[k,a] != 2:
                        school[k,a]= 3
print(school)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 3. 3. 3. 3. 3. 3. 3. 0. 0.]
 [0. 0. 3. 3. 3. 3. 3. 3. 3. 3. 0. 0.]
 [0. 0. 3. 3. 2. 2. 2. 2. 3. 3. 0. 0.]
 [0. 0. 3. 3. 2. 2. 2. 2. 3. 3. 0. 0.]
 [0. 0. 3. 3. 2. 2. 2. 2. 3. 3. 0. 0.]
 [0. 0. 3. 3. 2. 2. 2. 2. 3. 3. 0. 0.]
 [0. 0. 3. 3. 3. 3. 3. 3. 3. 3. 0. 0.]
 [0. 0. 3. 3. 3. 3. 3. 3. 3. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
